package com.restaurant.dao;

import com.restaurant.model.Notification;
import com.restaurant.util.DatabaseUtil;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * DAO for the {@code notification} table.
 * Used by {@link com.restaurant.service.ReservationNotificationService}
 * to persist and query notifications generated by the background daemon thread.
 */
public class NotificationDAO {

    /**
     * Returns true if a notification already exists for the given reservation.
     * Prevents the daemon from firing duplicate alerts on consecutive poll cycles.
     */
    public boolean existsForReservation(int reservationId) throws SQLException {
        String sql = "SELECT COUNT(*) FROM notification WHERE reservation_id = ?";
        try (PreparedStatement ps = DatabaseUtil.getConnection().prepareStatement(sql)) {
            ps.setInt(1, reservationId);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return rs.getInt(1) > 0;
            }
        }
        return false;
    }

    /** Persists a new Notification row and writes back the generated ID. */
    public int insert(Notification notification) throws SQLException {
        String sql = """
                INSERT INTO notification
                    (reservation_id, customer_id, content, notification_type, is_sent)
                VALUES (?, ?, ?, ?, ?)
                """;
        try (PreparedStatement ps = DatabaseUtil.getConnection()
                .prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, notification.getReservationId());
            if (notification.getCustomerId() != null) {
                ps.setInt(2, notification.getCustomerId());
            } else {
                ps.setNull(2, Types.INTEGER);
            }
            ps.setString(3, notification.getContent());
            ps.setString(4, notification.getNotificationType().name());
            ps.setBoolean(5, notification.isSent());
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) {
                    int id = keys.getInt(1);
                    notification.setNotificationId(id);
                    return id;
                }
            }
        }
        return -1;
    }

    /** Returns all unsent notifications (for dashboard alerts on startup). */
    public List<Notification> findUnsent() throws SQLException {
        List<Notification> list = new ArrayList<>();
        String sql = "SELECT * FROM notification WHERE is_sent = FALSE ORDER BY created_at";
        try (PreparedStatement ps = DatabaseUtil.getConnection().prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) list.add(mapRow(rs));
        }
        return list;
    }

    public void markSent(int notificationId) throws SQLException {
        String sql = "UPDATE notification SET is_sent = TRUE WHERE notification_id = ?";
        try (PreparedStatement ps = DatabaseUtil.getConnection().prepareStatement(sql)) {
            ps.setInt(1, notificationId);
            ps.executeUpdate();
        }
    }

    private Notification mapRow(ResultSet rs) throws SQLException {
        Notification n = new Notification();
        n.setNotificationId(rs.getInt("notification_id"));
        n.setReservationId(rs.getInt("reservation_id"));
        int cid = rs.getInt("customer_id");
        n.setCustomerId(rs.wasNull() ? null : cid);
        n.setContent(rs.getString("content"));
        n.setNotificationType(
                com.restaurant.model.enums.NotificationType.valueOf(rs.getString("notification_type")));
        n.setSent(rs.getBoolean("is_sent"));
        Timestamp ts = rs.getTimestamp("created_at");
        if (ts != null) n.setCreatedAt(ts.toLocalDateTime());
        return n;
    }
}
