package com.restaurant.model;

import com.restaurant.model.enums.NotificationType;
import java.time.LocalDateTime;

/**
 * Represents a system notification generated by the background daemon thread
 * when a reservation's time is approaching.
 */
public class Notification {
    private int notificationId;
    private int reservationId;
    private Integer customerId;
    private String content;
    private NotificationType notificationType;
    private boolean sent;
    private LocalDateTime createdAt;

    public Notification() {
        this.notificationType = NotificationType.SYSTEM;
        this.sent = false;
    }

    public int getNotificationId()                              { return notificationId; }
    public void setNotificationId(int notificationId)           { this.notificationId = notificationId; }
    public int getReservationId()                               { return reservationId; }
    public void setReservationId(int reservationId)             { this.reservationId = reservationId; }
    public Integer getCustomerId()                              { return customerId; }
    public void setCustomerId(Integer customerId)               { this.customerId = customerId; }
    public String getContent()                                  { return content; }
    public void setContent(String content)                      { this.content = content; }
    public NotificationType getNotificationType()               { return notificationType; }
    public void setNotificationType(NotificationType type)      { this.notificationType = type; }
    public boolean isSent()                                     { return sent; }
    public void setSent(boolean sent)                           { this.sent = sent; }
    public LocalDateTime getCreatedAt()                         { return createdAt; }
    public void setCreatedAt(LocalDateTime ts)                  { this.createdAt = ts; }

    @Override
    public String toString() { return "[" + notificationType + "] " + content; }
}